Change place of GUNPGHOME for apt-cyg.
In previous version, GNUPGHOME for apt-cyg had been set "$cache/apt-cyg/.gnupg".
But there are some inconveniences.
For example, if you downloaded apt-cyg into "$cache/", GNUPGHOME could not be initialized.
So this patch change GNUPGHOME for apt-cyg from "$cache/apt-cyg/.gnupg" to "$cache/.apt-cyg"

In additionally, a error handler for initializing GNUPGHOME is added.

diff --git a/apt-cyg b/apt-cyg
--- a/apt-cyg
+++ b/apt-cyg
@@ -199,11 +199,12 @@ function charch ()
 function init_gnupg ()
 {
   [ -z "$GPG" ] && return
-  export GNUPGHOME="$cache/apt-cyg/.gnupg"
-  echo $GNUPGHOME
+  export GNUPGHOME="$cache/.apt-cyg"
   if ! [ -d "$GNUPGHOME" ]; then
-    mkdir -p "$GNUPGHOME"
-    chmod 700 "$GNUPGHOME"
+    if ! { mkdir -p "$GNUPGHOME" && chmod 700 "$GNUPGHOME"; } then
+      echo -e "\e[31;1mError:\e[30;0m cannot initialize directory $GNUPGHOME"
+      exit 1
+    fi
   fi
   GPG_KEYRING=( --keyring pubring.gpg )
 }
