Support for multiple installation of cygwin. This commit relates to issue #47.

diff --git a/apt-cyg b/apt-cyg
--- a/apt-cyg
+++ b/apt-cyg
@@ -1468,13 +1468,26 @@ function apt-cyg-update-setup ()
   popd > /dev/null
 }
 
+function prepare_setup_rc ()
+{
+  local cache="$(apt-cyg-pathof cache)"
+  if ! ln -f /etc/setup/setup.rc "${cache%/}/" >&/dev/null; then
+    warning "\n\tFailed: ln -f /etc/setup/setup.rc \"${cache%/}/\"" \
+            "\n\tFall back: cp -a /etc/setup/setup.rc \"${cache%/}/\""
+    unlink "${cache%/}/setup.rc"
+    cp -a /etc/setup/setup.rc "${cache%/}/" \
+    || { error "Failed: cp -a /etc/setup/setup.rc \"${cache%/}/\""; exit 1; }
+  fi
+}
+
 function apt-cyg-setup ()
 {
   pushd "$(apt-cyg pathof cache)" > /dev/null
   
-  local setup=( "./${SETUP_EXE}" "$@" )
+  local setup=( "./${SETUP_EXE}" -R "$(cygpath -wa /)" "$@" )
   
   apt-cyg-update-setup
+  prepare_setup_rc
   "${setup[@]}"
   
   popd > /dev/null
@@ -1487,6 +1500,7 @@ function apt-cyg-dist-upgrade-no-ask ()
   pushd "$(apt-cyg-pathof cache)" > /dev/null
   
   apt-cyg-update-setup
+  prepare_setup_rc
   cygstart "$COMSPEC" /c 'ECHO Press any key to start dist-upgrade for cygwin '"$(current_cygarch)"' && PAUSE && START /WAIT '"${setup[@]}"' && ash -c "/bin/rebaseall -v" && ECHO dist-upgrade is finished && ECHO Press any key to exit && PAUSE' # '
   kill_all_cygwin_process
   
